---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: egress-gateway
  namespace: egress-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: egress-gateway
  namespace: egress-operator-system
rules:
- apiGroups:
  - policy
  resourceNames:
  - psp-10-privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: egress-gateway-binding
  namespace: egress-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: egress-gateway
subjects:
- kind: ServiceAccount
  name: egress-gateway
  namespace: egress-operator-system

---
apiVersion: egress.monzo.com/v1
kind: ExternalService
metadata:
  name: hn
spec:
  dnsName: google.com
  # optional, defaults to false, instructs dns server to rewrite queries for dnsName
  hijackDns: true
  ports:
  - port: 443
    # optional, defaults to TCP
    protocol: TCP
    containerPort: 443
  # optional, defaults to 3
  minReplicas: 1
  # optional, defaults to 12
  maxReplicas: 3
  # optional, defaults to 50
  targetCPUUtilizationPercentage: 30
  # optional, if not provided then defaults to 100m, 50Mi, 2, 1Gi
  resources:
    requests:
      cpu: "1"
      memory: 100Mi
    limits:
      cpu: "2"
      memory: 200Mi
